#cloud-config
hostname: ${name}
fqdn: ${name}.${base_domain}
preserve_hostname: false
manage_etc_hosts: true

users:
  - name: clouduser
    gecos: Cloud User
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: wheel
    lock_passwd: false
    # mypassword
    passwd: "$6$.JHdCXwZ7DbJhEv3$EgrqGuqJxsvGBXLskXJlKL93aCW1h6C/RHtqHuMA8oPGka1749xokt6lbCQz/uGokNUiHBRP7KceSPE3vPLfI."
    ssh_authorized_keys:
      - ${public_key}

disk_setup:
  /dev/sdb:
    table_type: gpt
    layout: true
    overwrite: false
  /dev/sdc:
    table_type: gpt
    layout: true
    overwrite: false
fs_setup:
  - label: artifactory # maximum 12 characters
    filesystem: xfs
    device: /dev/sdb1
    partition: auto
  - label: containers # maximum 12 characters
    filesystem: xfs
    device: /dev/sdc1
    partition: auto

mounts:
  - [ /dev/sdb1, /opt/artifactory, auto, "defaults,nofail", "0", "2" ]
  - [ /dev/sdc1, /var/lib/containers, auto, "defaults,nofail", "0", "2" ]

final_message: "The system is finally up, after $UPTIME seconds"
